
export const financeMissions=[
{id:'finance_offer_001',type:'application',title:'Listar 5 coisas que você sabe fazer',competency:'offer_discovery',minutes:15,energyCost:2,persistent:true,optional:false,requiresText:true,why:'Antes de vender, você precisa descobrir o que poderia oferecer.',focus:'Pense em habilidades simples: ensinar algo, consertar algo, organizar algo, ajudar alguém.',evidenceType:'text',evidenceText:'Listou possíveis habilidades para gerar renda.'},
{id:'finance_offer_002',type:'application',title:'Encontrar 3 problemas que pessoas próximas têm',competency:'offer_discovery',minutes:15,energyCost:2,persistent:true,optional:false,requiresText:true,why:'Dinheiro aparece quando você resolve problemas reais.',focus:'Não pense em produto ainda. Observe problemas pequenos que alguém pagaria para resolver.',evidenceType:'text',evidenceText:'Identificou problemas reais que poderia resolver.'},
{id:'finance_budget_001',type:'application',title:'Analisar seus últimos gastos',competency:'budget',minutes:15,energyCost:2,persistent:true,optional:false,requiresText:true,why:'O objetivo não é apenas anotar gastos. É encontrar padrões e vazamentos.',focus:'Identifique 1 gasto que poderia ter sido evitado e 1 melhoria possível.',evidenceType:'text',evidenceText:'Analisou seus últimos gastos.'},
{id:'finance_budget_002',type:'learning',title:'Aprender o que é orçamento pessoal',competency:'budget',minutes:15,energyCost:1,persistent:true,optional:false,requiresText:true,why:'Sem orçamento, você não sabe se está avançando ou apenas sobrevivendo.',focus:'Entenda gasto fixo, gasto variável e sobra mensal.',resourceUrl:'https://www.youtube.com/results?search_query=or%C3%A7amento+pessoal+educa%C3%A7%C3%A3o+financeira',evidenceType:'learning',evidenceText:'Estudou orçamento pessoal.'},
{id:'finance_saving_001',type:'action',title:'Separar R$10 para sua reserva',competency:'saving',minutes:5,energyCost:1,persistent:true,optional:false,why:'O hábito de separar dinheiro vem antes do valor alto.',focus:'Separe o dinheiro antes de gastar com outra coisa.',evidenceType:'money',moneyAmount:10,evidenceText:'Guardou R$10.'},
{id:'finance_sales_001',type:'impact',title:'Oferecer uma solução simples para uma pessoa',competency:'sales',minutes:20,energyCost:4,persistent:true,optional:false,requiresText:true,why:'Vender é uma competência essencial para aumentar renda.',focus:'Use apenas se você já sabe o que pode oferecer.',evidenceType:'text',evidenceText:'Praticou uma oferta simples.'},
{id:'finance_discipline_001',type:'reflection',title:'Responder: o que mais dificultou hoje?',competency:'discipline',minutes:3,energyCost:1,persistent:true,optional:false,requiresText:true,why:'O sistema precisa entender seus obstáculos reais para adaptar o caminho.',focus:'Responda sem justificar. Apenas registre a verdade.',evidenceType:'reflection',evidenceText:'Registrou dificuldade do dia.'}
];
export const skillMissions=[
{id:'skill_clarity_001',type:'application',title:'Definir exatamente o que você quer aprender',competency:'clarity',minutes:10,energyCost:1,persistent:true,optional:false,requiresText:true,why:'Aprender uma habilidade ampla demais faz a pessoa se perder.',focus:'Escreva o que você quer conseguir fazer na prática.',evidenceType:'text',evidenceText:'Definiu o objetivo prático da habilidade.'},
{id:'skill_learning_001',type:'learning',title:'Encontrar um recurso inicial confiável',competency:'learning_path',minutes:15,energyCost:1,persistent:true,optional:false,requiresText:true,why:'Antes de estudar muito, escolha uma fonte inicial e evite pular de vídeo em vídeo.',focus:'Procure um vídeo ou artigo introdutório e escreva por que escolheu esse recurso.',evidenceType:'text',evidenceText:'Escolheu um recurso inicial de aprendizagem.'},
{id:'skill_practice_001',type:'application',title:'Fazer a primeira prática pequena',competency:'practice',minutes:20,energyCost:2,persistent:true,optional:false,requiresText:true,why:'Habilidade não se desenvolve só consumindo conteúdo. Precisa prática.',focus:'Faça uma tentativa pequena e registre o que conseguiu fazer.',evidenceType:'text',evidenceText:'Fez a primeira prática da habilidade.'}
];
