export const financeMissions = [
  {id:'finance_budget_001',type:'application',title:'Analisar seus últimos gastos',competency:'budget',minutes:15,energyCost:2,persistent:true,optional:false,why:'O objetivo não é apenas anotar gastos. É encontrar padrões e vazamentos.',focus:'Identifique 1 gasto que poderia ter sido evitado.',evidenceType:'action',evidenceText:'Analisou seus últimos gastos.'},
  {id:'finance_budget_002',type:'learning',title:'Aprender o que é orçamento pessoal',competency:'budget',minutes:15,energyCost:1,persistent:true,optional:false,why:'Sem orçamento, você não sabe se está avançando ou apenas sobrevivendo.',focus:'Entenda gasto fixo, gasto variável e sobra mensal.',resourceUrl:'https://www.youtube.com/results?search_query=or%C3%A7amento+pessoal+educa%C3%A7%C3%A3o+financeira',evidenceType:'learning',evidenceText:'Estudou orçamento pessoal.'},
  {id:'finance_saving_001',type:'action',title:'Separar R$10 para sua reserva',competency:'saving',minutes:5,energyCost:1,persistent:true,optional:false,why:'O hábito de separar dinheiro vem antes do valor alto.',focus:'Separe o dinheiro antes de gastar com outra coisa.',evidenceType:'money',moneyAmount:10,evidenceText:'Guardou R$10.'},
  {id:'finance_income_001',type:'impact',title:'Listar 3 formas reais de ganhar R$10',competency:'income_generation',minutes:20,energyCost:3,persistent:true,optional:false,why:'Aumentar renda começa com enxergar possibilidades concretas.',focus:'Liste opções possíveis na sua realidade, não ideias fantasiosas.',evidenceType:'action',evidenceText:'Listou formas de gerar renda extra.'},
  {id:'finance_sales_001',type:'impact',title:'Oferecer algo simples para uma pessoa',competency:'sales',minutes:20,energyCost:4,persistent:true,optional:false,why:'Vender é uma competência essencial para aumentar renda.',focus:'O objetivo hoje é praticar a oferta, não virar vendedor profissional.',evidenceType:'action',evidenceText:'Praticou uma oferta simples.'},
  {id:'finance_discipline_001',type:'reflection',title:'Responder: o que mais dificultou hoje?',competency:'discipline',minutes:3,energyCost:1,persistent:true,optional:false,why:'O sistema precisa entender seus obstáculos reais para adaptar o caminho.',focus:'Responda sem justificar. Apenas registre a verdade.',evidenceType:'reflection',evidenceText:'Registrou dificuldade do dia.'},
  {id:'finance_advance_001',type:'impact',title:'Conseguir ou economizar R$10 extras',competency:'income_generation',minutes:20,energyCost:4,persistent:false,optional:true,why:'Acelera o objetivo sem esperar o próximo ciclo.',focus:'Pode ser venda, economia, comissão, recuperação de dívida ou serviço simples.',evidenceType:'money',moneyAmount:10,evidenceText:'Gerou ou economizou R$10 extras.'},
  {id:'finance_investing_001',type:'learning',title:'Aprender liquidez e risco antes de investir',competency:'investing',minutes:20,energyCost:2,persistent:true,optional:false,why:'Antes de investir, você precisa saber quando o dinheiro não deve ser investido.',focus:'Entenda por que reserva de emergência exige liquidez e baixo risco.',resourceUrl:'https://www.youtube.com/results?search_query=liquidez+risco+renda+fixa+reserva+de+emerg%C3%AAncia',evidenceType:'learning',evidenceText:'Estudou liquidez e risco.'}
];
