
export const financeMissions = [
  {id:"finance_offer_001",type:"application",title:"Listar 5 coisas que você sabe fazer",competency:"offer_discovery",minutes:15,energyCost:2,persistent:true,optional:false,requiresText:true,textHelp:"Escreva habilidades simples. Exemplo: ensinar espanhol, organizar algo, consertar algo, ajudar alguém com tecnologia, fazer entrega, limpar, traduzir.",why:"Antes de vender, você precisa descobrir o que poderia oferecer.",focus:"Pense em habilidades simples que alguém poderia pagar para receber.",evidenceType:"text",evidenceText:"Listou possíveis habilidades para gerar renda."},
  {id:"finance_offer_002",type:"application",title:"Encontrar 3 problemas que pessoas próximas têm",competency:"offer_discovery",minutes:15,energyCost:2,persistent:true,optional:false,requiresText:true,textHelp:"Escreva 3 problemas reais. Exemplo: alguém precisa aprender espanhol, alguém precisa de ajuda com mudança, alguém quer organizar documentos.",why:"Dinheiro aparece quando você resolve problemas reais.",focus:"Não pense em produto ainda. Observe problemas pequenos.",evidenceType:"text",evidenceText:"Identificou problemas reais que poderia resolver."},
  {id:"finance_budget_001",type:"application",title:"Analisar seus últimos gastos",competency:"budget",minutes:15,energyCost:2,persistent:true,optional:false,requiresText:true,textHelp:"Escreva: 1 gasto evitável, 1 padrão que percebeu e 1 ajuste que fará amanhã.",why:"O objetivo não é apenas anotar gastos. É encontrar padrões e vazamentos.",focus:"Identifique melhoria concreta.",evidenceType:"text",evidenceText:"Analisou seus últimos gastos."},
  {id:"finance_budget_002",type:"learning",title:"Aprender o que é orçamento pessoal",competency:"budget",minutes:15,energyCost:1,persistent:true,optional:false,quiz:[
    {q:"O que é um gasto fixo?",options:["Um gasto que acontece com frequência e muda pouco","Uma compra por impulso","Dinheiro investido"],correct:0},
    {q:"Qual é o objetivo do orçamento?",options:["Controlar e decidir melhor","Ficar rico em uma semana","Nunca gastar dinheiro"],correct:0},
    {q:"O que você deve identificar primeiro?",options:["Vazamentos de dinheiro","Criptomoedas","Cartão novo"],correct:0}
  ],why:"Sem orçamento, você não sabe se está avançando ou apenas sobrevivendo.",focus:"Entenda gasto fixo, gasto variável e sobra mensal.",resourceUrl:"https://www.youtube.com/results?search_query=or%C3%A7amento+pessoal+educa%C3%A7%C3%A3o+financeira",evidenceType:"learning",evidenceText:"Estudou orçamento pessoal."},
  {id:"finance_saving_001",type:"action",title:"Separar R$10 para sua reserva",competency:"saving",minutes:5,energyCost:1,persistent:true,optional:false,why:"O hábito de separar dinheiro vem antes do valor alto.",focus:"Separe o dinheiro antes de gastar com outra coisa.",evidenceType:"money",moneyAmount:10,evidenceText:"Guardou R$10."},
  {id:"finance_discipline_001",type:"reflection",title:"Responder: o que mais dificultou hoje?",competency:"discipline",minutes:3,energyCost:1,persistent:true,optional:false,requiresText:true,textHelp:"Escreva o obstáculo real: tempo, energia, dinheiro, vergonha, preguiça, confusão ou outro.",why:"O sistema precisa entender seus obstáculos reais.",focus:"Responda sem justificar. Apenas registre a verdade.",evidenceType:"reflection",evidenceText:"Registrou dificuldade do dia."}
];
