export const diagnosticQuestions = [
  {id:'main_goal',title:'Qual é seu objetivo principal agora?',type:'choice',options:[{value:'financial_freedom',label:'Liberdade financeira'},{value:'health',label:'Melhorar saúde'},{value:'career',label:'Crescer na carreira'},{value:'learn_skill',label:'Aprender uma habilidade'}]},
  {id:'daily_time',title:'Quanto tempo você consegue manter por dia?',type:'choice',options:[{value:15,label:'15 minutos'},{value:30,label:'30 minutos'},{value:60,label:'60 minutos'},{value:90,label:'90 minutos ou mais'}]},
  {id:'financial_stage',title:'Qual frase descreve melhor sua vida financeira?',type:'choice',options:[{value:'surviving',label:'Vivo no limite e quase nunca sobra dinheiro'},{value:'sometimes_save',label:'Às vezes consigo guardar, mas não mantenho'},{value:'monthly_save',label:'Já guardo dinheiro quase todo mês'},{value:'investing',label:'Já invisto e quero evoluir'}]},
  {id:'income',title:'Qual é sua renda mensal aproximada?',type:'number',placeholder:'Ex: 2500'},
  {id:'current_savings',title:'Quanto você tem guardado hoje?',type:'number',placeholder:'Ex: 200'},
  {id:'main_blocker',title:'O que mais trava seu avanço hoje?',type:'choice',options:[{value:'low_income',label:'Ganho pouco'},{value:'spending',label:'Gasto sem controlar'},{value:'discipline',label:'Falta constância'},{value:'knowledge',label:'Não sei o caminho'},{value:'sales',label:'Não sei vender ou gerar renda extra'}]}
];
export function createDiagnostic(answers){const time=Number(answers.daily_time||30);const income=Number(answers.income||0);const savings=Number(answers.current_savings||0);let rhythm='constancia';if(time>=60)rhythm='equilibrio';if(time>=90)rhythm='intensivo';const competencies={budget:20,saving:20,income_generation:20,sales:15,investing:10,discipline:35};if(answers.financial_stage==='sometimes_save'){competencies.budget=35;competencies.saving=35}if(answers.financial_stage==='monthly_save'){competencies.budget=60;competencies.saving=65;competencies.discipline=55}if(answers.financial_stage==='investing'){competencies.budget=75;competencies.saving=75;competencies.investing=55;competencies.discipline=65}if(answers.main_blocker==='sales'||answers.main_blocker==='low_income'){competencies.income_generation=15;competencies.sales=10}const bottleneck=findBottleneck(competencies,answers.main_blocker);return{goal:answers.main_goal||'financial_freedom',dailyTime:time,rhythm,income,savings,blocker:answers.main_blocker,competencies,bottleneck,createdAt:new Date().toISOString()}}
export function findBottleneck(competencies,blocker){if(blocker==='sales')return'sales';if(blocker==='low_income')return'income_generation';if(blocker==='spending')return'budget';if(blocker==='discipline')return'discipline';if(blocker==='knowledge')return'budget';return Object.entries(competencies).sort((a,b)=>a[1]-b[1])[0][0]}
