
export const diagnosticQuestions=[
{id:"main_goal",title:"Qual é seu objetivo principal agora?",type:"choice",options:[{value:"financial_freedom",label:"Liberdade financeira"},{value:"learn_skill",label:"Aprender uma habilidade"},{value:"career",label:"Crescer na carreira"},{value:"health",label:"Melhorar saúde"}]},
{id:"daily_time",title:"Quanto tempo você consegue manter por dia?",type:"choice",options:[{value:15,label:"15 minutos"},{value:30,label:"30 minutos"},{value:60,label:"60 minutos"},{value:90,label:"90 minutos ou mais"}]},
{id:"skill_to_learn",title:"Que habilidade você quer aprender?",type:"text",showIf:{main_goal:"learn_skill"},placeholder:"Ex: programação, espanhol, design, vendas, edição de vídeo"},
{id:"skill_level",title:"Qual é seu nível nessa habilidade?",type:"choice",showIf:{main_goal:"learn_skill"},options:[{value:"zero",label:"Começando do zero"},{value:"basic",label:"Já sei o básico"},{value:"intermediate",label:"Intermediário"},{value:"advanced",label:"Avançado"}]},
{id:"financial_stage",title:"Qual frase descreve melhor sua vida financeira?",type:"choice",showIf:{main_goal:"financial_freedom"},options:[{value:"surviving",label:"Vivo no limite e quase nunca sobra dinheiro"},{value:"sometimes_save",label:"Às vezes consigo guardar, mas não mantenho"},{value:"monthly_save",label:"Já guardo dinheiro quase todo mês"},{value:"investing",label:"Já invisto e quero evoluir"}]},
{id:"income",title:"Qual é sua renda mensal aproximada?",type:"number",showIf:{main_goal:"financial_freedom"},placeholder:"Ex: 2500"},
{id:"current_savings",title:"Quanto você tem guardado hoje?",type:"number",showIf:{main_goal:"financial_freedom"},placeholder:"Ex: 200"},
{id:"has_job",title:"Você tem emprego ou renda fixa hoje?",type:"choice",showIf:{main_goal:"financial_freedom"},options:[{value:"yes",label:"Sim"},{value:"no",label:"Não"},{value:"unstable",label:"Tenho renda instável"}]},
{id:"has_offer",title:"Você tem algo claro para oferecer ou vender hoje?",type:"choice",showIf:{main_goal:"financial_freedom"},options:[{value:"yes",label:"Sim, já sei o que posso oferecer"},{value:"maybe",label:"Talvez, tenho habilidades mas não sei vender"},{value:"no",label:"Não tenho produto nem serviço definido"}]},
{id:"main_blocker",title:"O que mais trava seu avanço hoje?",type:"choice",showIf:{main_goal:"financial_freedom"},options:[{value:"low_income",label:"Ganho pouco"},{value:"spending",label:"Gasto sem controlar"},{value:"discipline",label:"Falta constância"},{value:"knowledge",label:"Não sei o caminho"},{value:"sales",label:"Não sei vender ou gerar renda extra"}]}
];
export function getVisibleQuestions(answers){return diagnosticQuestions.filter(q=>!q.showIf||Object.entries(q.showIf).every(([k,v])=>answers[k]===v));}
export function createDiagnostic(a){const time=Number(a.daily_time||30);let rhythm=time>=90?'intensivo':time>=60?'equilibrio':'constancia';if(a.main_goal==='learn_skill')return{goal:'learn_skill',skillToLearn:a.skill_to_learn||'habilidade escolhida',skillLevel:a.skill_level||'zero',dailyTime:time,rhythm,bottleneck:'learning_path',competencies:{discipline:30,learning:20,practice:10,clarity:15},createdAt:new Date().toISOString()};const income=Number(a.income||0),savings=Number(a.current_savings||0);const competencies={budget:20,saving:20,income_generation:15,offer_discovery:10,sales:5,investing:10,discipline:35};if(a.financial_stage==='sometimes_save'){competencies.budget=35;competencies.saving=35}if(a.financial_stage==='monthly_save'){competencies.budget=60;competencies.saving=65;competencies.discipline=55}if(a.financial_stage==='investing'){competencies.budget=75;competencies.saving=75;competencies.investing=55;competencies.discipline=65}let bottleneck='budget';if(a.main_blocker==='sales'||a.main_blocker==='low_income')bottleneck=a.has_offer==='yes'?'sales':'offer_discovery';if(a.main_blocker==='spending')bottleneck='budget';if(a.main_blocker==='discipline')bottleneck='discipline';if(a.main_blocker==='knowledge')bottleneck='budget';return{goal:'financial_freedom',dailyTime:time,rhythm,income,savings,hasJob:a.has_job,hasOffer:a.has_offer,blocker:a.main_blocker,competencies,bottleneck,createdAt:new Date().toISOString()};}
